version: 2.1

orbs:
    node: circleci/node@7.0.0

jobs:
    build-and-test:
        executor:
            name: node/default
            tag: "18.20.0"
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
            - run:
                  name: Install
                  command: npm ci
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                  name: Audit
                  command: npm audit --audit-level=low
            - run:
                  name: Test
                  command: npm run test
            - run:
                  name: Build
                  command: npm run build
            - persist_to_workspace:
                  root: .
                  paths: .
    deploy-package:
        executor:
            name: node/default
            tag: "18.20.0"
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Authenticate with registry
                  command: |
                      echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
            - run:
                  name: List all files
                  command: ls -al
            - run:
                  name: Publish package
                  command: |
                      PACKAGE_VERSION=$(cat ./package.json \
                          | grep '"version":' \
                          | head -1 \
                          | awk -F: '{ print $2 }' \
                          | sed 's/[",]//g' \
                          | tr -d '[:space:]')
                        IS_BETA="false"
                        IS_ALPHA="false"

                        if [[ $PACKAGE_VERSION == *"-beta"* ]]; then
                          IS_BETA="true"
                        elif [[ $PACKAGE_VERSION == *"-alpha"* ]]; then
                          IS_ALPHA="true"
                        fi

                        if [ $IS_BETA == "true" ]; then
                          npm publish --access public --tag beta
                        elif [ $IS_ALPHA == "true" ]; then
                          npm publish --access public --tag alpha
                        else
                          npm publish --access public
                        fi

workflows:
    build-deploy:
        jobs:
            - build-and-test:
                  filters:
                      tags:
                          only: /.*/
            # - hold:
            #       type: approval
            #       requires:
            #           - build-and-test
            #       filters:
            #           tags:
            #               only: /^v.*/
            #           branches:
            #               ignore: /.*/
            - deploy-package:
                  requires:
                      - build-and-test
                  filters:
                      tags:
                          only: /^v.*/
                      branches:
                          ignore: /.*/
